version: '2'
services:
    hedwig-mongodb:
        container_name: hedwig-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/hedwig/mongodb/:/data/db/
